# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      #- image: circleci/php:latest
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4
      - image: php:7.2-apache
      - image: mysql:5.7
      

    working_directory: ~/repo

    steps:
    
      - run:
         name: Install PHP libcu-dev
         command: sudo apt-get install libicu-dev
         
      - run:
         name: Install PHP intl
         command: sudo docker-php-ext-install intl
         
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist
      
      - run: composer require --dev phpunit/phpunit:"6.0"

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
        
      # run tests!
      - run: vendor/bin/phpunit